/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ferrari.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Ferrari(props) {
  const { nodes, materials } = useGLTF('models/ferrari.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lamborghini_Aventador_Wheel_FR.geometry} material={materials._Lamborghini_AventadorLamborghini_Aventador_BodySG} position={[-0.129, 0.013, -1.355]} scale={[0.005, 0.007, 0.007]} />
      <group position={[0, -0.008, -0.008]} scale={[0.869, 1, 1]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials['Material.012']} />
      </group>
      <mesh geometry={nodes.Lamborghini_Aventador_Wheel_FR001.geometry} material={materials['_Lamborghini_AventadorLamborghini_Aventador_BodySG.001']} position={[-0.129, 0.013, -3.235]} scale={[0.005, 0.007, 0.007]} />
      <mesh geometry={nodes.Lamborghini_Aventador_Wheel_FR002.geometry} material={materials['_Lamborghini_AventadorLamborghini_Aventador_BodySG.002']} position={[0.127, 0.02, -1.793]} rotation={[-Math.PI, 0.011, -Math.PI]} scale={[0.005, 0.007, 0.007]} />
      <mesh geometry={nodes.Lamborghini_Aventador_Wheel_FR003.geometry} material={materials['_Lamborghini_AventadorLamborghini_Aventador_BodySG.003']} position={[0.127, 0.013, 0.083]} rotation={[-Math.PI, 0.011, -Math.PI]} scale={[0.005, 0.007, 0.007]} />
      <mesh geometry={nodes.Lamborghini_Aventador_Wheel_FR004.geometry} material={materials['_Lamborghini_AventadorLamborghini_Aventador_BodySG.004']} position={[0.127, 0.02, -1.793]} rotation={[-Math.PI, 0.011, -Math.PI]} scale={[0.005, 0.007, 0.007]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.006']} position={[0.379, 0.428, -3.06]} rotation={[1.563, -0.9, -0.01]} scale={0.03} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.008']} position={[0.421, 0.428, -3.06]} rotation={[1.563, -0.9, -0.01]} scale={0.03} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.005']} position={[-0.374, 0.428, -3.06]} rotation={[1.563, -0.9, -0.01]} scale={0.03} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.007']} position={[-0.416, 0.428, -3.06]} rotation={[1.563, -0.9, -0.01]} scale={0.03} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.009']} position={[-0.396, 0.591, -3.046]} rotation={[1.563, -0.9, -0.01]} scale={[0.044, 0.006, 0.044]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.010']} position={[0.393, 0.591, -3.046]} rotation={[1.563, -0.9, -0.01]} scale={[0.044, 0.006, 0.044]} />
    </group>
  )
}

useGLTF.preload('models/ferrari.glb')
