# Generated by Django 5.2 on 2025-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('top_speed', models.CharField(max_length=50)),
                ('acceleration', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=100)),
                ('horsepower', models.CharField(max_length=50)),
            ],
        ),
    ]
